name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          🚧🚨
          Marking this issue as stale since there has been no activity in the last 60 days.
          Remove stale label, comment or this issue will be closed in 30 days ⌛️
          🚨🚧
        stale-issue-label: stale
        days-before-stale: 60
        days-before-close: 30
